# Generated by Django 3.2.19 on 2023-05-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='donated',
            field=models.BooleanField(default=False),
        ),
    ]
