# Generated by Django 3.2.19 on 2023-05-14 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('plans', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_comments', to='profiles.profile')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='plans.plan')),
            ],
        ),
    ]
