# Generated by Django 3.2.19 on 2023-05-14 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_auto_20230514_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='image_urlfield',
        ),
    ]
